<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'login' => [[], ['_controller' => 'App\\Controller\\HomeController::login'], [], [['text', '/']], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\HomeController::register'], [], [['text', '/registerTest']], [], []],
    'invitations_index' => [[], ['_controller' => 'App\\Controller\\InvitationsController::index'], [], [['text', '/amis/']], [], []],
    'invitations_new' => [[], ['_controller' => 'App\\Controller\\InvitationsController::new'], [], [['text', '/amis/new']], [], []],
    'invitations_show' => [['id'], ['_controller' => 'App\\Controller\\InvitationsController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/amis']], [], []],
    'invitations_edit' => [['id'], ['_controller' => 'App\\Controller\\InvitationsController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/amis']], [], []],
    'invitations_delete' => [['id'], ['_controller' => 'App\\Controller\\InvitationsController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/amis']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'share' => [[], ['_controller' => 'App\\Controller\\ShareController::index'], [], [['text', '/share']], [], []],
    'tasks_index' => [[], ['_controller' => 'App\\Controller\\TasksController::index'], [], [['text', '/dashboard/']], [], []],
    'tasks_new' => [[], ['_controller' => 'App\\Controller\\TasksController::new'], [], [['text', '/dashboard/new']], [], []],
    'tasks_edit' => [['id'], ['_controller' => 'App\\Controller\\TasksController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/dashboard']], [], []],
    'tasks_delete' => [['id'], ['_controller' => 'App\\Controller\\TasksController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/dashboard']], [], []],
];
