<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDrfsAOl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDrfsAOl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDrfsAOl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDrfsAOl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDrfsAOl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DrfsAOl',
    'container.build_id' => 'bbf68f23',
    'container.build_time' => 1585828938,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDrfsAOl');
