<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE7MRpVU\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE7MRpVU/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE7MRpVU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE7MRpVU\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerE7MRpVU\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'E7MRpVU',
    'container.build_id' => 'd2cf8026',
    'container.build_time' => 1584449666,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE7MRpVU');
